name: TapGame

options:
  bundleIdPrefix: com.nhan

targets:
  TapGame:
    type: application
    platform: iOS

    sources:
      - .

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.nhan.tapgame

    info:
      path: Info.plist
